// Code generated by MockGen. DO NOT EDIT.
// Source: db/sqlc/store.go

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/bergamo17/aila/db/sqlc"
	gomock "github.com/golang/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateNote mocks base method.
func (m *MockStore) CreateNote(ctx context.Context, arg sqlc.CreateNoteParams) (sqlc.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, arg)
	ret0, _ := ret[0].(sqlc.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockStoreMockRecorder) CreateNote(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockStore)(nil).CreateNote), ctx, arg)
}

// CreateSubject mocks base method.
func (m *MockStore) CreateSubject(ctx context.Context, arg sqlc.CreateSubjectParams) (sqlc.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubject", ctx, arg)
	ret0, _ := ret[0].(sqlc.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubject indicates an expected call of CreateSubject.
func (mr *MockStoreMockRecorder) CreateSubject(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubject", reflect.TypeOf((*MockStore)(nil).CreateSubject), ctx, arg)
}

// CreateTask mocks base method.
func (m *MockStore) CreateTask(ctx context.Context, arg sqlc.CreateTaskParams) (sqlc.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, arg)
	ret0, _ := ret[0].(sqlc.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockStoreMockRecorder) CreateTask(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockStore)(nil).CreateTask), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(ctx context.Context, arg sqlc.CreateUserParams) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), ctx, arg)
}

// DeleteNote mocks base method.
func (m *MockStore) DeleteNote(ctx context.Context, arg sqlc.DeleteNoteParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockStoreMockRecorder) DeleteNote(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockStore)(nil).DeleteNote), ctx, arg)
}

// DeleteTask mocks base method.
func (m *MockStore) DeleteTask(ctx context.Context, arg sqlc.DeleteTaskParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockStoreMockRecorder) DeleteTask(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockStore)(nil).DeleteTask), ctx, arg)
}

// GetNote mocks base method.
func (m *MockStore) GetNote(ctx context.Context, arg sqlc.GetNoteParams) (sqlc.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNote", ctx, arg)
	ret0, _ := ret[0].(sqlc.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNote indicates an expected call of GetNote.
func (mr *MockStoreMockRecorder) GetNote(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNote", reflect.TypeOf((*MockStore)(nil).GetNote), ctx, arg)
}

// GetTask mocks base method.
func (m *MockStore) GetTask(ctx context.Context, arg sqlc.GetTaskParams) (sqlc.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, arg)
	ret0, _ := ret[0].(sqlc.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockStoreMockRecorder) GetTask(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockStore)(nil).GetTask), ctx, arg)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(ctx context.Context, username string) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, username)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), ctx, username)
}

// GetUserByEmail mocks base method.
func (m *MockStore) GetUserByEmail(ctx context.Context, email string) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockStoreMockRecorder) GetUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockStore)(nil).GetUserByEmail), ctx, email)
}

// ListNotesBySubject mocks base method.
func (m *MockStore) ListNotesBySubject(ctx context.Context, arg sqlc.ListNotesBySubjectParams) ([]sqlc.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotesBySubject", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotesBySubject indicates an expected call of ListNotesBySubject.
func (mr *MockStoreMockRecorder) ListNotesBySubject(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotesBySubject", reflect.TypeOf((*MockStore)(nil).ListNotesBySubject), ctx, arg)
}

// ListNotesByUser mocks base method.
func (m *MockStore) ListNotesByUser(ctx context.Context, userID int64) ([]sqlc.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotesByUser", ctx, userID)
	ret0, _ := ret[0].([]sqlc.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotesByUser indicates an expected call of ListNotesByUser.
func (mr *MockStoreMockRecorder) ListNotesByUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotesByUser", reflect.TypeOf((*MockStore)(nil).ListNotesByUser), ctx, userID)
}

// ListSubjectByUser mocks base method.
func (m *MockStore) ListSubjectByUser(ctx context.Context, userID int64) ([]sqlc.ListSubjectByUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubjectByUser", ctx, userID)
	ret0, _ := ret[0].([]sqlc.ListSubjectByUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubjectByUser indicates an expected call of ListSubjectByUser.
func (mr *MockStoreMockRecorder) ListSubjectByUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubjectByUser", reflect.TypeOf((*MockStore)(nil).ListSubjectByUser), ctx, userID)
}

// ListTaskByStatus mocks base method.
func (m *MockStore) ListTaskByStatus(ctx context.Context, arg sqlc.ListTaskByStatusParams) ([]sqlc.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTaskByStatus", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTaskByStatus indicates an expected call of ListTaskByStatus.
func (mr *MockStoreMockRecorder) ListTaskByStatus(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTaskByStatus", reflect.TypeOf((*MockStore)(nil).ListTaskByStatus), ctx, arg)
}

// ListTaskBySubject mocks base method.
func (m *MockStore) ListTaskBySubject(ctx context.Context, arg sqlc.ListTaskBySubjectParams) ([]sqlc.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTaskBySubject", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTaskBySubject indicates an expected call of ListTaskBySubject.
func (mr *MockStoreMockRecorder) ListTaskBySubject(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTaskBySubject", reflect.TypeOf((*MockStore)(nil).ListTaskBySubject), ctx, arg)
}

// ListTaskByUser mocks base method.
func (m *MockStore) ListTaskByUser(ctx context.Context, userID int64) ([]sqlc.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTaskByUser", ctx, userID)
	ret0, _ := ret[0].([]sqlc.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTaskByUser indicates an expected call of ListTaskByUser.
func (mr *MockStoreMockRecorder) ListTaskByUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTaskByUser", reflect.TypeOf((*MockStore)(nil).ListTaskByUser), ctx, userID)
}

// UpdateNote mocks base method.
func (m *MockStore) UpdateNote(ctx context.Context, arg sqlc.UpdateNoteParams) (sqlc.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNote", ctx, arg)
	ret0, _ := ret[0].(sqlc.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MockStoreMockRecorder) UpdateNote(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockStore)(nil).UpdateNote), ctx, arg)
}

// UpdateTask mocks base method.
func (m *MockStore) UpdateTask(ctx context.Context, arg sqlc.UpdateTaskParams) (sqlc.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, arg)
	ret0, _ := ret[0].(sqlc.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockStoreMockRecorder) UpdateTask(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockStore)(nil).UpdateTask), ctx, arg)
}

// UpdateTaskStatus mocks base method.
func (m *MockStore) UpdateTaskStatus(ctx context.Context, arg sqlc.UpdateTaskStatusParams) (sqlc.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", ctx, arg)
	ret0, _ := ret[0].(sqlc.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockStoreMockRecorder) UpdateTaskStatus(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockStore)(nil).UpdateTaskStatus), ctx, arg)
}
