// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Note struct {
	ID        int64              `json:"id"`
	SubjectID int64              `json:"subject_id"`
	Content   pgtype.Text        `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Title     string             `json:"title"`
}

type NoteAttachment struct {
	ID        int64              `json:"id"`
	NotesID   int64              `json:"notes_id"`
	FileName  string             `json:"file_name"`
	FilePath  string             `json:"file_path"`
	FileType  pgtype.Text        `json:"file_type"`
	FileSize  pgtype.Int8        `json:"file_size"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Schedule struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	SubjectID   int64              `json:"subject_id"`
	TaskID      pgtype.Int8        `json:"task_id"`
	Title       string             `json:"title"`
	EventDate   pgtype.Date        `json:"event_date"`
	Reminder    pgtype.Bool        `json:"reminder"`
	IsCompleted bool               `json:"is_completed"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	RefreshToken string             `json:"refresh_token"`
	UserAgent    string             `json:"user_agent"`
	ClientIp     string             `json:"client_ip"`
	IsBlocked    bool               `json:"is_blocked"`
	ExpiredAt    pgtype.Timestamptz `json:"expired_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Subject struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	SubjectName string             `json:"subject_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	SubjectID  int64              `json:"subject_id"`
	Title      string             `json:"title"`
	TaskStatus string             `json:"task_status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                int64              `json:"id"`
	Username          string             `json:"username"`
	HashedPassword    string             `json:"hashed_password"`
	Fullname          string             `json:"fullname"`
	Email             string             `json:"email"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
