// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: note.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (
    subject_id, title, content
) VALUES (
    $1, $2, $3
) RETURNING id, subject_id, content, created_at, updated_at, title
`

type CreateNoteParams struct {
	SubjectID int64       `json:"subject_id"`
	Title     string      `json:"title"`
	Content   pgtype.Text `json:"content"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote, arg.SubjectID, arg.Title, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes n
WHERE n.id = $1
    AND subject_id IN (
        SELECT id FROM subjects WHERE user_id = $2
    )
`

type DeleteNoteParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) error {
	_, err := q.db.Exec(ctx, deleteNote, arg.ID, arg.UserID)
	return err
}

const getNote = `-- name: GetNote :one
SELECT n.id, n.subject_id, n.content, n.created_at, n.updated_at, n.title 
FROM notes n
JOIN subjects s ON s.id = n.subject_id
WHERE n.id = $1 AND s.user_id = $2 
LIMIT 1
`

type GetNoteParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetNote(ctx context.Context, arg GetNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, getNote, arg.ID, arg.UserID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
	)
	return i, err
}

const listNotesBySubject = `-- name: ListNotesBySubject :many
SELECT n.id, n.subject_id, n.content, n.created_at, n.updated_at, n.title
FROM notes n
JOIN subjects s ON s.id = n.subject_id
WHERE n.subject_id = $1 AND s.user_id = $2
ORDER BY n.created_at DESC
`

type ListNotesBySubjectParams struct {
	SubjectID int64 `json:"subject_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) ListNotesBySubject(ctx context.Context, arg ListNotesBySubjectParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesBySubject, arg.SubjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesByUser = `-- name: ListNotesByUser :many
SELECT n.id, n.subject_id, n.content, n.created_at, n.updated_at, n.title
FROM notes n
JOIN subjects s ON s.id = n.subject_id
WHERE s.user_id = $1
ORDER BY n.created_at DESC
`

func (q *Queries) ListNotesByUser(ctx context.Context, userID int64) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes n
SET content = $3, updated_at = clock_timestamp()
WHERE n.id = $1
    AND subject_id IN (
        SELECT id FROM subjects WHERE user_id = $2
    )
RETURNING id, subject_id, content, created_at, updated_at, title
`

type UpdateNoteParams struct {
	ID      int64       `json:"id"`
	UserID  int64       `json:"user_id"`
	Content pgtype.Text `json:"content"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote, arg.ID, arg.UserID, arg.Content)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
	)
	return i, err
}
