// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BlockSession(ctx context.Context, id pgtype.UUID) error
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteNote(ctx context.Context, arg DeleteNoteParams) error
	DeleteSubject(ctx context.Context, arg DeleteSubjectParams) error
	DeleteTask(ctx context.Context, arg DeleteTaskParams) error
	GetNote(ctx context.Context, arg GetNoteParams) (Note, error)
	GetSession(ctx context.Context, id pgtype.UUID) (Session, error)
	GetSubjectById(ctx context.Context, id int64) (Subject, error)
	GetTask(ctx context.Context, arg GetTaskParams) (Task, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListNotesBySubject(ctx context.Context, arg ListNotesBySubjectParams) ([]Note, error)
	ListNotesByUser(ctx context.Context, userID int64) ([]Note, error)
	ListSubjectByUser(ctx context.Context, userID int64) ([]ListSubjectByUserRow, error)
	ListTaskByStatus(ctx context.Context, arg ListTaskByStatusParams) ([]Task, error)
	ListTaskBySubject(ctx context.Context, arg ListTaskBySubjectParams) ([]Task, error)
	ListTaskByUser(ctx context.Context, userID int64) ([]Task, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
