// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error)
	CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteNote(ctx context.Context, arg DeleteNoteParams) error
	DeleteTask(ctx context.Context, arg DeleteTaskParams) error
	GetNote(ctx context.Context, arg GetNoteParams) (Note, error)
	GetTask(ctx context.Context, arg GetTaskParams) (Task, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListNotesBySubject(ctx context.Context, arg ListNotesBySubjectParams) ([]Note, error)
	ListNotesByUser(ctx context.Context, userID int64) ([]Note, error)
	ListSubjectByUser(ctx context.Context, userID int64) ([]ListSubjectByUserRow, error)
	ListTaskByStatus(ctx context.Context, arg ListTaskByStatusParams) ([]Task, error)
	ListTaskBySubject(ctx context.Context, arg ListTaskBySubjectParams) ([]Task, error)
	ListTaskByUser(ctx context.Context, userID int64) ([]Task, error)
	UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
