// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (user_id, subject_id, task_id, title, event_date, reminder, type, start_time, end_time)
VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, subject_id, task_id, title, event_date, reminder, is_completed, created_at, type, start_time, end_time
`

type CreateScheduleParams struct {
	UserID    int64       `json:"user_id"`
	SubjectID int64       `json:"subject_id"`
	TaskID    pgtype.Int8 `json:"task_id"`
	Title     string      `json:"title"`
	EventDate pgtype.Date `json:"event_date"`
	Reminder  pgtype.Bool `json:"reminder"`
	Type      string      `json:"type"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.UserID,
		arg.SubjectID,
		arg.TaskID,
		arg.Title,
		arg.EventDate,
		arg.Reminder,
		arg.Type,
		arg.StartTime,
		arg.EndTime,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.TaskID,
		&i.Title,
		&i.EventDate,
		&i.Reminder,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.Type,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules
WHERE id = $1 AND user_id = $2
`

type DeleteScheduleParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) error {
	_, err := q.db.Exec(ctx, deleteSchedule, arg.ID, arg.UserID)
	return err
}

const getScheduleById = `-- name: GetScheduleById :one
SELECT id, user_id, subject_id, task_id, title, event_date, reminder, is_completed, created_at, type, start_time, end_time FROM schedules
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetScheduleByIdParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetScheduleById(ctx context.Context, arg GetScheduleByIdParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, getScheduleById, arg.ID, arg.UserID)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.TaskID,
		&i.Title,
		&i.EventDate,
		&i.Reminder,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.Type,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const listScheduleByDate = `-- name: ListScheduleByDate :many
SELECT id, user_id, subject_id, task_id, title, event_date, reminder, is_completed, created_at, type, start_time, end_time FROM schedules
WHERE user_id = $1 AND event_date = $2
ORDER BY created_at ASC
`

type ListScheduleByDateParams struct {
	UserID    int64       `json:"user_id"`
	EventDate pgtype.Date `json:"event_date"`
}

func (q *Queries) ListScheduleByDate(ctx context.Context, arg ListScheduleByDateParams) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listScheduleByDate, arg.UserID, arg.EventDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubjectID,
			&i.TaskID,
			&i.Title,
			&i.EventDate,
			&i.Reminder,
			&i.IsCompleted,
			&i.CreatedAt,
			&i.Type,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleByUserAndDateRange = `-- name: ListScheduleByUserAndDateRange :many
SELECT id, user_id, subject_id, task_id, title, event_date, reminder, is_completed, created_at, type, start_time, end_time FROM schedules
WHERE user_id = $1 
    AND event_date BETWEEN $2 AND $3
ORDER BY event_date ASC
`

type ListScheduleByUserAndDateRangeParams struct {
	UserID      int64       `json:"user_id"`
	EventDate   pgtype.Date `json:"event_date"`
	EventDate_2 pgtype.Date `json:"event_date_2"`
}

func (q *Queries) ListScheduleByUserAndDateRange(ctx context.Context, arg ListScheduleByUserAndDateRangeParams) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listScheduleByUserAndDateRange, arg.UserID, arg.EventDate, arg.EventDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubjectID,
			&i.TaskID,
			&i.Title,
			&i.EventDate,
			&i.Reminder,
			&i.IsCompleted,
			&i.CreatedAt,
			&i.Type,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingSchedule = `-- name: ListUpcomingSchedule :many
SELECT id, user_id, subject_id, task_id, title, event_date, reminder, is_completed, created_at, type, start_time, end_time FROM schedules
WHERE user_id = $1 AND event_date >= $2
ORDER BY event_date ASC
LIMIT 3
`

type ListUpcomingScheduleParams struct {
	UserID    int64       `json:"user_id"`
	EventDate pgtype.Date `json:"event_date"`
}

func (q *Queries) ListUpcomingSchedule(ctx context.Context, arg ListUpcomingScheduleParams) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listUpcomingSchedule, arg.UserID, arg.EventDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubjectID,
			&i.TaskID,
			&i.Title,
			&i.EventDate,
			&i.Reminder,
			&i.IsCompleted,
			&i.CreatedAt,
			&i.Type,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE schedules
SET subject_id = $3,
    task_id = $4,
    title = $5,
    event_date = $6,
    start_time = $7,
    end_time = $8,
    type = $9,
    reminder = $10
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, subject_id, task_id, title, event_date, reminder, is_completed, created_at, type, start_time, end_time
`

type UpdateScheduleParams struct {
	ID        int64       `json:"id"`
	UserID    int64       `json:"user_id"`
	SubjectID int64       `json:"subject_id"`
	TaskID    pgtype.Int8 `json:"task_id"`
	Title     string      `json:"title"`
	EventDate pgtype.Date `json:"event_date"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
	Type      string      `json:"type"`
	Reminder  pgtype.Bool `json:"reminder"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, updateSchedule,
		arg.ID,
		arg.UserID,
		arg.SubjectID,
		arg.TaskID,
		arg.Title,
		arg.EventDate,
		arg.StartTime,
		arg.EndTime,
		arg.Type,
		arg.Reminder,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.TaskID,
		&i.Title,
		&i.EventDate,
		&i.Reminder,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.Type,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const updateScheduleStatus = `-- name: UpdateScheduleStatus :one
UPDATE schedules
SET is_completed = $3
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, subject_id, task_id, title, event_date, reminder, is_completed, created_at, type, start_time, end_time
`

type UpdateScheduleStatusParams struct {
	ID          int64 `json:"id"`
	UserID      int64 `json:"user_id"`
	IsCompleted bool  `json:"is_completed"`
}

func (q *Queries) UpdateScheduleStatus(ctx context.Context, arg UpdateScheduleStatusParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, updateScheduleStatus, arg.ID, arg.UserID, arg.IsCompleted)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.TaskID,
		&i.Title,
		&i.EventDate,
		&i.Reminder,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.Type,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}
