// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subject.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (
    user_id, subject_name, color
) VALUES (
    $1, $2, $3
) RETURNING id, user_id, subject_name, created_at, color, updated_at
`

type CreateSubjectParams struct {
	UserID      int64  `json:"user_id"`
	SubjectName string `json:"subject_name"`
	Color       string `json:"color"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, createSubject, arg.UserID, arg.SubjectName, arg.Color)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectName,
		&i.CreatedAt,
		&i.Color,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubject = `-- name: DeleteSubject :exec
DELETE FROM subjects
WHERE id = $1 AND user_id = $2
`

type DeleteSubjectParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteSubject(ctx context.Context, arg DeleteSubjectParams) error {
	_, err := q.db.Exec(ctx, deleteSubject, arg.ID, arg.UserID)
	return err
}

const getSubjectById = `-- name: GetSubjectById :one
SELECT id, user_id, subject_name, created_at, color, updated_at
FROM subjects
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSubjectById(ctx context.Context, id int64) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubjectById, id)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectName,
		&i.CreatedAt,
		&i.Color,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubjectByUser = `-- name: ListSubjectByUser :many
SELECT s.id, s.user_id, s.subject_name, s.created_at, s.color, s.updated_at, COUNT(n.id) AS notes_count
FROM subjects AS s
LEFT JOIN notes n ON n.subject_id = s.id
WHERE s.user_id = $1
GROUP BY s.id
ORDER BY s.created_at DESC
`

type ListSubjectByUserRow struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	SubjectName string             `json:"subject_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Color       string             `json:"color"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	NotesCount  int64              `json:"notes_count"`
}

func (q *Queries) ListSubjectByUser(ctx context.Context, userID int64) ([]ListSubjectByUserRow, error) {
	rows, err := q.db.Query(ctx, listSubjectByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubjectByUserRow{}
	for rows.Next() {
		var i ListSubjectByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubjectName,
			&i.CreatedAt,
			&i.Color,
			&i.UpdatedAt,
			&i.NotesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubject = `-- name: UpdateSubject :one
UPDATE subjects
SET subject_name = $3, color = $4, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, subject_name, created_at, color, updated_at
`

type UpdateSubjectParams struct {
	ID          int64  `json:"id"`
	UserID      int64  `json:"user_id"`
	SubjectName string `json:"subject_name"`
	Color       string `json:"color"`
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, updateSubject,
		arg.ID,
		arg.UserID,
		arg.SubjectName,
		arg.Color,
	)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectName,
		&i.CreatedAt,
		&i.Color,
		&i.UpdatedAt,
	)
	return i, err
}
