// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    user_id, subject_id, title, description
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, subject_id, title, task_status, created_at, updated_at, position, description
`

type CreateTaskParams struct {
	UserID      int64       `json:"user_id"`
	SubjectID   int64       `json:"subject_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.UserID,
		arg.SubjectID,
		arg.Title,
		arg.Description,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.Title,
		&i.TaskStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
		&i.Description,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1 AND user_id = $2
`

type DeleteTaskParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.UserID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, user_id, subject_id, title, task_status, created_at, updated_at, position, description FROM tasks
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetTaskParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.Title,
		&i.TaskStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
		&i.Description,
	)
	return i, err
}

const listTaskByStatus = `-- name: ListTaskByStatus :many
SELECT id, user_id, subject_id, title, task_status, created_at, updated_at, position, description FROM tasks
WHERE user_id = $1 AND task_status = $2
ORDER BY created_at DESC
`

type ListTaskByStatusParams struct {
	UserID     int64  `json:"user_id"`
	TaskStatus string `json:"task_status"`
}

func (q *Queries) ListTaskByStatus(ctx context.Context, arg ListTaskByStatusParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTaskByStatus, arg.UserID, arg.TaskStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubjectID,
			&i.Title,
			&i.TaskStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Position,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskBySubject = `-- name: ListTaskBySubject :many
SELECT id, user_id, subject_id, title, task_status, created_at, updated_at, position, description FROM tasks
WHERE subject_id = $1 AND user_id = $2
ORDER BY created_at DESC
`

type ListTaskBySubjectParams struct {
	SubjectID int64 `json:"subject_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) ListTaskBySubject(ctx context.Context, arg ListTaskBySubjectParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTaskBySubject, arg.SubjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubjectID,
			&i.Title,
			&i.TaskStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Position,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskByUser = `-- name: ListTaskByUser :many
SELECT id, user_id, subject_id, title, task_status, created_at, updated_at, position, description FROM tasks
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTaskByUser(ctx context.Context, userID int64) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTaskByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubjectID,
			&i.Title,
			&i.TaskStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Position,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByUser = `-- name: ListTasksByUser :many
SELECT t.id, t.user_id, t.subject_id, t.title, t.task_status, t.created_at, t.updated_at, t.position, t.description
FROM tasks t
WHERE t.user_id = $1
ORDER BY t.task_status, t."position"
`

func (q *Queries) ListTasksByUser(ctx context.Context, userID int64) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubjectID,
			&i.Title,
			&i.TaskStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Position,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shiftTaskPositionDown = `-- name: ShiftTaskPositionDown :exec
UPDATE tasks
SET position = position - 1
WHERE user_id = $1 AND task_status = $2
    AND position > $3 AND position <= $4
    AND id != $5
`

type ShiftTaskPositionDownParams struct {
	UserID     int64  `json:"user_id"`
	TaskStatus string `json:"task_status"`
	Position   int64  `json:"position"`
	Position_2 int64  `json:"position_2"`
	ID         int64  `json:"id"`
}

func (q *Queries) ShiftTaskPositionDown(ctx context.Context, arg ShiftTaskPositionDownParams) error {
	_, err := q.db.Exec(ctx, shiftTaskPositionDown,
		arg.UserID,
		arg.TaskStatus,
		arg.Position,
		arg.Position_2,
		arg.ID,
	)
	return err
}

const shiftTaskPositionUp = `-- name: ShiftTaskPositionUp :exec
UPDATE tasks 
SET position = position + 1
WHERE user_id = $1 AND task_status = $2
    AND position >= $3 AND position < $4
    AND id != $5
`

type ShiftTaskPositionUpParams struct {
	UserID     int64  `json:"user_id"`
	TaskStatus string `json:"task_status"`
	Position   int64  `json:"position"`
	Position_2 int64  `json:"position_2"`
	ID         int64  `json:"id"`
}

func (q *Queries) ShiftTaskPositionUp(ctx context.Context, arg ShiftTaskPositionUpParams) error {
	_, err := q.db.Exec(ctx, shiftTaskPositionUp,
		arg.UserID,
		arg.TaskStatus,
		arg.Position,
		arg.Position_2,
		arg.ID,
	)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $3, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, subject_id, title, task_status, created_at, updated_at, position, description
`

type UpdateTaskParams struct {
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
	Title  string `json:"title"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask, arg.ID, arg.UserID, arg.Title)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.Title,
		&i.TaskStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
		&i.Description,
	)
	return i, err
}

const updateTaskPosition = `-- name: UpdateTaskPosition :one
UPDATE tasks
SET position = $3, task_status = $4, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, subject_id, title, task_status, created_at, updated_at, position, description
`

type UpdateTaskPositionParams struct {
	ID         int64  `json:"id"`
	UserID     int64  `json:"user_id"`
	Position   int64  `json:"position"`
	TaskStatus string `json:"task_status"`
}

func (q *Queries) UpdateTaskPosition(ctx context.Context, arg UpdateTaskPositionParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskPosition,
		arg.ID,
		arg.UserID,
		arg.Position,
		arg.TaskStatus,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.Title,
		&i.TaskStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
		&i.Description,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET task_status = $3, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, subject_id, title, task_status, created_at, updated_at, position, description
`

type UpdateTaskStatusParams struct {
	ID         int64  `json:"id"`
	UserID     int64  `json:"user_id"`
	TaskStatus string `json:"task_status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus, arg.ID, arg.UserID, arg.TaskStatus)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubjectID,
		&i.Title,
		&i.TaskStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
		&i.Description,
	)
	return i, err
}
